DEFAULT_ENTITIES = ["PATIENT", "PER", "LOC", "ORG", "FAC", "GPE", "PROV", "DATE", "NORP", "CODE", "MAIL", "PHONE", "URL"]
DEFAULT_EXTRA_PER_MATCHING = True
DEFAULT_NER_MODEL = "NER/models/deployed/deployed_v2.2"