import spacy
import json
from spacy.tokens import DocBin
from tqdm import tqdm
from spacy.util import filter_spans

from data_generation import to_spacy_format


def load_training_data(file_path: str):
    """Loads training data from a JSON file in the format generated by data_generation module."""
    with open(file_path, 'r', encoding='utf-8-sig') as f:
        data = json.load(f)

    # Checks if data is not in spaCy format
    if isinstance(data, list) and all(isinstance(item, dict) for item in data):
        data = [to_spacy_format(example) for example in data]

    training_data = []
    for item in data:
        entities = []
        for ent in item[1]['entities']:
            start, end, label = ent[0], ent[1], ent[2]
            entities.append((start, end, label))
        training_data.append({'text': item[0], 'entities': entities})

    return training_data


def to_docbin_format(training_data, permitted_labels: set[str] = None) -> DocBin:
    """Converts training data in the spaCy format into spaCy's DocBin format."""
    nlp = spacy.blank('it')
    doc_bin = DocBin()

    for training_example in tqdm(training_data):
        text = training_example['text']
        labels = training_example['entities']
        doc = nlp.make_doc(text)
        ents = []
        for start, end, label in labels:
            span = doc.char_span(start, end, label=label, alignment_mode="contract")
            if span is None:
                print(f"Skipping entity [{text[start:end]}] in text [{text}] due to misalignment.")
            elif permitted_labels and label not in permitted_labels:
                continue
            else:
                ents.append(span)
        filtered_ents = filter_spans(ents)
        doc.ents = filtered_ents
        doc_bin.add(doc)
    return doc_bin

def load_docbin(file_path: str) -> DocBin:
    """Loads a DocBin object from a .spacy file."""
    doc_bin = DocBin().from_disk(file_path)
    return doc_bin

def combine_docbins(docbins: list[DocBin]) -> DocBin:
    """Combines multiple DocBin objects into one."""
    combined_docbin = DocBin()
    for db in docbins:
        for doc in db.get_docs(spacy.blank('it').vocab):
            combined_docbin.add(doc)
    return combined_docbin